### ISSUE TITLE
PC Slows down horrendously over time while using a PS Navigation Controller

### ISSUE THREAD

**Issue by tunbridgep** [ViGEm/FireShock#27]
Hi! I am using the PS3 Navigation Controller that came with the PS Move.

This driver is very good for getting this device working, and it works flawlessly in-game, except for one very major issue.

Whenever I try to play a game, and I use the controller in conjunction with the mouse (it is a 1 handed controller), my PC starts to slow down exponentially, and it eventually gets so slow and so laggy that the sound starts popping instead of sounding normal. Hard to describe, I know, and I can't record the effect unfortunately.

I am running Windows 7, using the latest version of the driver available on the releases page. My PS Navi is connected via USB. I run all my games through Steam, with big picture mode for configuring the move controller. I have other controllers that work totally fine with Steam's big picture mode, so the issue is not with Steam.

Disconnecting the controller IMMEDIATELY fixes the issue

**Comment by JoshWobbles** [comment]
Related to https://github.com/nefarius/FireShock/issues/4

**Comment by nefarius** [comment]
I should really delete the releases. Reminder set.

**Comment by mirh** [comment]
Those just work for DS3 tbh..

**Comment by JoshWobbles** [comment]
Was the move or nav controller issue ever figured out? ive been AWOL for a while and missed a few things.

**Comment by mirh** [comment]
Nope, total rewrite of the driver.. And crossed fingers.

**Comment by nefarius** [comment]
The only media where up-to-date news is circulating is my Discord.

**Comment by CareFudundae** [comment]
I had the same issue, but changing to a usb 3.0 port fixed it for me... not sure why. got this idea from: https://github.com/ViGEm/FireShock/issues/4#issuecomment-317292914

**Comment by nefarius** [comment]
Since this issue originated from major version 1 release - which I have now officially deprecated - it's no more relevant and closed.
