### ISSUE TITLE
Cryptominer still planned?

### ISSUE THREAD

**Issue by notwarhol** [ViGEm/FireShock#32]
Is the cryptominer mentioned in https://vigem.org/2018/04/01/vigem-goes-crypto/ still planned for being added in? Will the option exist to opt-out for the user? Please remove if this is the incorrect place to inquire.

**Comment by JoshWobbles** [comment]
@sylveon it’s only a couple days old, what’s your point?

**Comment by sylveon** [comment]
[April 1st](https://en.wikipedia.org/wiki/April_Fools'_Day)

**Comment by notwarhol** [comment]
HA! Got me good if that was the intent!

**Comment by nefarius** [comment]
![](https://i.ebayimg.com/images/g/FnQAAOSwEeFVEPB~/s-l300.jpg)
